version: "3.9"
services:
  reth_init:
    image: "ghcr.io/paradigmxyz/reth" # Sets up the genesis configuration for the reth Engram Tokio client from a JSON file.
    container_name: reth_init
    command: init --datadir=/execution --chain=custom_config_data/genesis.json
    volumes:
      - ./execution:/execution
      - ./custom_config_data:/custom_config_data

  reth_el:
    image: "ghcr.io/paradigmxyz/reth" # Runs the striatum execution client with the specified networks.
    container_name: reth_el
    restart: on-failure
    command:
      - node
      - --datadir=/execution
      - --chain=/custom_config_data/genesis.json
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots
      - --ws.origins=*
      - --discovery.port=30303
      - --port=30303
      - --identity=reth-lh  # change with your discordusername without hashtag numbers
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/custom_config_data/jwtsecret
      - --authrpc.addr=0.0.0.0
      - --metrics=0.0.0.0:9001
      - --bootnodes=enode://7fb8b8c922c034de8e08c83ab332c944d15ee2283aa22ba4554fc2fe217688d25bb3629613a8e981b3aaa8c15d93b17d07da3289731637b4c87530492e52ba5f@159.223.32.178:30303
      - --trusted-peers=enode://7fb8b8c922c034de8e08c83ab332c944d15ee2283aa22ba4554fc2fe217688d25bb3629613a8e981b3aaa8c15d93b17d07da3289731637b4c87530492e52ba5f@159.223.32.178:30303
    ports:
      - 8545:8545 # engine-rpc
      - 8546:8546 # ws-api
      - 8551:8551 # rpc-api
      - 9001:9001 # metrics
      - 30303:30303/tcp # bootnodes
      - 30303:30303/udp # bootnodes
    depends_on:
      reth_init:
        condition: service_completed_successfully
    volumes:
      - ./execution:/execution
      - ./custom_config_data:/custom_config_data

  lighthouse_cl:
    image: "sigp/lighthouse:v4.5.0"  # Runs a Lighthouse beacon chain from a specified genesis state created in the previous step
    container_name: lighthouse_cl
    restart: on-failure
    command:
      - lighthouse
      - bn
      - --eth1
      - --staking
      - --http
      - --http-port=5052
      - --http-allow-sync-stalled 
      - --http-address=0.0.0.0
      - --subscribe-all-subnets
      - --http-allow-origin=*
      - --debug-level=info
      - --datadir=/consensus
      - --testnet-dir=/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=0.0.0.0 # Change with your public IPAddress
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --discovery-port=9000
      - --port=9002
      - --genesis-backfill
      - --target-peers=400
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --graffiti=reth-lh
      - --boot-nodes=enr:-MS4QM-MntzP5SV2kCYGAqkPRftijGUk9YLlhMjbFNmbO4UFDuh7hWOfVfXgcmt68jemKyMQwIkdZDjLSYRaxOa0265Fh2F0dG5ldHOI__________-EZXRoMpBINphZQAABMP__________gmlkgnY0gmlwhJ_fILKEcXVpY4IjKYlzZWNwMjU2azGhA3mfOFKLjNnqjvCNXTWNiJiaXHbF2rs3hj8hsAWZGxbViHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo,enr:-MS4QCqpMiJtAOVRUc0rjS_9vHDPQwf8C7lkmSpzdZ0qp__iX6t78Cb6O8DK7RUgO5GIw56qDKz6et3c9hJRUkVHl2xGh2F0dG5ldHOI__________-EZXRoMpBINphZQAABMP__________gmlkgnY0gmlwhJ_fILKEcXVpY4IjLIlzZWNwMjU2azGhAzoKhhH6nsT1R0NtuvmphYf_fAOh3aUiU_0EJiXmbCeGiHN5bmNuZXRzD4N0Y3CCIyuDdWRwgiMr
      - --execution-endpoints=http://reth_el:8551
      - --eth1-endpoints=http://reth_el:8545
      - --execution-jwt=/custom_config_data/jwtsecret
    depends_on:
      reth_el:
        condition: service_started
    ports:
      - 5052:5052 # ethereum-node-record
      - 5054:5054 # metrics
      - 9000:9000/tcp # ENR port tcp
      - 9000:9000/udp # ENR port udp
    volumes:
      - ./consensus:/consensus
      - ./custom_config_data:/custom_config_data
