version: "3.9"
services:
  lighthouse_init:
    image: "sigp/lighthouse:v4.5.0" # Initialize and import keystore from staking_cli to lighthouse client.
    container_name: lighthouse_init
    command: lighthouse account validator import --testnet-dir=/custom_config_data --datadir=/validator --directory=/validator_keys --password-file=/custom_config_data/password.txt --reuse-password
    volumes:
      - ./custom_config_data:/custom_config_data
      - ./validator:/validator
      - ./validator_keys:/validator_keys

  lighthouse_vc:
    image: "sigp/lighthouse:v4.5.0"  # Runs a Lighthouse validator from a specified consensus state created in the previous step
    container_name: lighthouse_vc
    restart: on-failure
    command:
      - lighthouse
      - vc
      - --http
      - --unencrypted-http-transport
      - --init-slashing-protection
      - --http-allow-origin=*
      - --http-port=5062
      - --http-address=0.0.0.0
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5064
      - --metrics-allow-origin=*
      - --datadir=/validator
      - --testnet-dir=/custom_config_data
      - --suggested-fee-recipient=0xe5F92D6f076b00C85404A0005EaE9f7DF91d4846 # SwissEngine Node
      - --graffiti=Participate-01
      - --beacon-nodes=http://172.30.0.3:5052
    depends_on:
      lighthouse_init:
        condition: service_completed_successfully
    volumes:
      - ./custom_config_data:/custom_config_data
      - ./validator:/validator
    ports:
      - 5062:5062
      - 5064:5064
