#
# Metrics services -- provides a web GUI to monitor Lighthouse nodes.
#
version: "3.3"

services:
    prometheus:
      build:
      context: prometheus
      restart: always
      source: ./scrape-targets
      target: /prometheus/targets
      volumes:
        - prometheus-data:/prometheus
        - type: bind
      network_mode: host

    grafana:
      build:
      context: grafana
      restart: always
      volumes:
            - grafana-data:/var/lib/grafana
      network_mode: host
      volumes:
            grafana-data:/var/lib/grafana
            prometheus-data:/prometheus
            targets:
